### ISSUE TITLE
Add .tech account to needed groups

### ISSUE THREAD

**Issue by johnrossini** [NetAppDocs/virtual-desktop-service#164]
Page: [Create a Domain Admin (
a .tech account needs to be a member of the Level3 Technicians group.  if that group doesn't exist it needs to be a member of the CW-Infrastructure group.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @johnrossini - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
