### ISSUE TITLE
stray line in document header impacting localized output

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/virtual-desktop-service#296]
@tvanroo - A problem was reported against the non-English instances of [this page](https://docs.netapp.com/us-en/virtual-desktop-service/Architectural.Wildcard_SSL_certificate_renewal_process.html). 

![image](https://user-images.githubusercontent.com/56453501/166934442-92078e67-d6b6-4e0d-9dc7-94d4f04207f6.png)

This was originally triaged as a system issue, since the English correctly displays the image and the non-English do not. However, the current thinking is that the root cause is an extra line in the document header that should also be causing the error in English but inexplicably is not. 

Please update [this file](https://github.com/NetAppDocs/virtual-desktop-service/blob/main/sub.Architectural.Wildcard_SSL_certificate_renewal_process.adoc?plain=1) deleting the blank lines before and after the page title. (Technically both are incorrect, though it's the line after the title, the current line 9, that is the probable culprit.)

````
---
sidebar: sidebar
permalink: Architectural.Wildcard_SSL_certificate_renewal_process.html
summary: Wildcard SSL certificate renewal process
keywords:
---

= Wildcard SSL Certificate Renewal Process

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords:
````

Tag me on the PR or comment here when the update is merged to main and I'll handle the validation.

**Comment by ntap-bmegan** [comment]
@tvanroo - Can you handle or assign this?

**Comment by tvanroo** [comment]
Thank you, I’ve merged the pull request, it should finish updates in 15-20 mins.

Best,
Toby

Toby vanRoojen – Spot PC
Spot by NetApp
206-650-5466 mobile - ***@***.******@***.***>

**Comment by ntap-bmegan** [comment]
@tvanroo - The good news is that the images display now. But there's an unrelated (I think) difference that doesn't make sense to me. I don't see anything in the EN source that would explain it, and it's not in the EN. But, just to cover the bases, can you confirm that you didn't do anything to create a mini-TOC visible on the page? Showing EN on the left and DE on the right for quick comparison. The blue highlight on the German page is the header of the mystery mini-TOC. 

![image](https://user-images.githubusercontent.com/56453501/210422706-b36c00f2-b4a4-43d8-998e-884a56c458e7.png)

I'm pretty sure that this is a random thing that's going wrong, but just wanted to double-check.
